// Generated by CoffeeScript 1.6.1
(function() {
  var example;

  example = {};

  $(function() {
    var columns, data, datatable, fistNameFormatter, i, rowFormatter, store;
    fistNameFormatter = function(tdEl, column, data) {
      if (!(data.id % 10)) {
        $(tdEl).css("background", "rgb(199, 255, 199)");
      }
      return tdEl.appendChild(document.createTextNode(data.first_name));
    };
    rowFormatter = function(trEl, data) {
      if (!(data.id % 20)) {
        return trEl.className += "error";
      }
    };
    columns = [
      {
        key: "id",
        label: "#",
        sortable: false,
        hidden: false,
        width: 20
      }, {
        key: "hidden",
        label: "Hidden",
        sortable: false,
        hidden: true
      }, {
        key: "first_name",
        label: "First Name",
        formatter: fistNameFormatter,
        sortable: true,
        hidden: false
      }, {
        key: "last_name",
        label: "Last Name",
        formatter: null,
        sortable: true,
        hidden: false
      }
    ];
    data = [];
    i = 1;
    while (i < 200) {
      data.push({
        "id": i,
        "hidden": i,
        "first_name": "First Name " + i,
        "last_name": "Last Name " + i
      });
      i++;
    }
    store = new Ex.ArrayStore({
      data: data
    });
    return datatable = new Ex.DataTable("table", {
      columns: columns,
      store: store,
      rowFormatter: rowFormatter,
      /*paginator: new Ex.Paginator
        container: '.pagination'
        totalRecords: 200
        rowsPerPage: 10
        rowsPerPageSelect: "#rows-per-page"
      filters: [
        new Ex.Filter.Search container: "#search"
      ]
      */

      sortedBy: {
        key: "id",
        dir: "ASC"
      }
    }, $("#add-row").click(function() {
      store.getData().unshift(data[0]);
      return datatable.refresh();
    }), $("#update-row").click(function() {
      store.getData(0).first_name = "Pupkin";
      return datatable.refresh();
    }), $("#delete-row").click(function() {
      store.remove(0);
      return datatable.refresh();
    }), $("#show-col").click(function() {
      return datatable.showColumn("hidden");
    }), $("#hide-col").click(function() {
      return datatable.hideColumn("id");
    }), $("#delete-col").click(function() {
      return datatable.removeColumn("first_name");
    }), $("#add-col").click(function() {
      return datatable.addColumn(columns[2], 2);
    }));
  });

}).call(this);
