// Generated by CoffeeScript 1.5.0
(function() {
  var example;

  example = {};

  $(function() {
    var columns, data, fields, fistNameFormatter, i, rowFormatter, store;
    fistNameFormatter = function(tdEl, column, data) {
      if (!(data.id % 10)) {
        tdEl.css("background", "rgb(199, 255, 199)");
      }
      return tdEl.text(data.first_name);
    };
    rowFormatter = function(trEl, data) {
      if (!(data.id % 20)) {
        return trEl.addClass("error");
      }
    };
    columns = [
      {
        key: "id",
        label: "#",
        sortable: true,
        hidden: true
      }, {
        key: "first_name",
        label: "First Name",
        formatter: fistNameFormatter,
        sortable: true,
        hidden: false
      }, {
        key: "last_name",
        label: "Last Name",
        formatter: null,
        sortable: true,
        hidden: false
      }
    ];
    fields = ["id", "first_name", "last_name"];
    data = [];
    i = 1;
    while (i < 200) {
      data.push({
        "id": i,
        "first_name": "First Name " + i,
        "last_name": "Last Name " + i
      });
      i++;
    }
    store = new Ex.ArrayStore({
      data: data
    });
    return example.datatable = new Ex.DataTable("table", {
      columns: columns,
      fields: fields,
      store: store,
      rowFormatter: rowFormatter,
      sortedBy: {
        key: "id",
        dir: "ASC"
      }
    });
  });

}).call(this);
